apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spotify-clone
  description: Spotify Clone
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - react
spec:
  type: website
  lifecycle: production
  owner: mtavares21
  system: public-websites
